### PR TITLE
Fix #41

### LINKED ISSUE #41: AutoSlider indicator Icon position change in Home page
## Issue Type:
- [ ] New UI Suggestion
- [ ] Suggestion for existing UI
- [ ] UI implementation
- [x] others

## Description:
On the homepage, the AutoSlider's indicator Icon position should be change. It should be placed at the bottom of the picture.

## ScreenShots / Video:
auto_slider_pos_change

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

### PR DESCRIPTION
**Pull request by AgarwalsRahul**
Change the position of the auto slider indicator

### CODE REVIEW

**Comment by HeySitam** [comment]
bro would you please fetch the upstream  to this branch ?

**Comment by AgarwalsRahul** [comment]
It is showing the branch has some conflict that needs to be resolved.

**Comment by HeySitam** [comment]
Can you resolve it manually?

**Comment by HeySitam** [comment]
Else you can make another pr

**Comment by AgarwalsRahul** [comment]
I have resolved the conflict.

**Comment by HeySitam** [comment]
great. thanks for the pr.

**Pull request merged**
