### PR TITLE
Fixed #40 : Implemented and navigate to IT Fragment

### LINKED ISSUE #40: No UI for Department of Information and Technology
## Issue Type:
- [x] UI implementation

## Description:
There is nothing happening while clicking on Department of Information and Technology.
And there is no OnClick and not even any Fragment Implemented for that.

## ScreenShots / Video:
See Nothing Happening in the screen when I click on Department of Computer Science.
https://user-images.githubusercontent.com/76530270/156896082-a8b710a3-b70b-450e-8af1-7303a441f6d3.mp4

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

I want to Implement this Fragment and set onClick also. Please assign me this issue.

### PR DESCRIPTION
**Pull request by MohitGupta121**
Fixed #40  Implemented and navigate to Information and Technology Fragment.

Below is the demo video:-

https://user-images.githubusercontent.com/76530270/170952499-7c8d2ede-b0c4-4d1f-a50f-abdcbc9999e1.mp4

### CODE REVIEW

**Comment by MohitGupta121** [comment]
@sitamadex11 can you please have a look on this till leaderboard of gssoc closed.

**Comment by MohitGupta121** [comment]
@sitamadex11 And can you please add level and gssoc tag in this

**Comment by MohitGupta121** [comment]
Thanks you bhaiya ❤

**Comment by HeySitam** [comment]
Welcome❤️

**Pull request merged**
